- front-end/package-lock.json
- front-end/package.json
- front-end/src/auxiliary/Comment.css
- front-end/src/auxiliary/Comment.js
- front-end/src/auxiliary/Showcase.js
Added Comment component as discussed. Can be viewed in showcase tab. Can anyone check and merge my request?
> Added: Comment Component

- front-end/src/auxiliary/PostContent.css
- front-end/src/auxiliary/PostContent.js
- front-end/src/auxiliary/Showcase.js
I added post content js and css file to make the post component.
> added:postcontent

- front-end/src/App.js
- front-end/src/auxiliary/Commented.css
- front-end/src/auxiliary/Commented_List.css
- front-end/src/auxiliary/Commented_List.js
- front-end/src/auxiliary/Liked.css
- front-end/src/auxiliary/Liked.js
- front-end/src/community/Liked_List.css
- front-end/src/community/Liked_List.js
Add: added Liked_List page and Liked component. The url for Liked_List page is '/likes'
Fix: fix back button in comment page
Fix: fix css in comment_like page
> Liked history

- front-end/src/community/Commented_List.js
- front-end/src/community/Liked_List.js
* Update: update backup api in `Liked_List.js` and `Commented_List.js` #105 #91 #93
> Update: update backup api in Liked_List.js and Commented_List.js

- front-end/package-lock.json
- front-end/package.json
- front-end/src/community/Community.css
- front-end/src/community/Community.js
- front-end/src/community/Message_History.css
- front-end/src/community/Message_History.js
> User story/46 104/task/67/add community page

- front-end/src/App.css
- front-end/src/App.js
- front-end/src/auxiliary/Loginform.css
- front-end/src/auxiliary/PostContent_noAction.css
- front-end/src/auxiliary/PostContent_noAction.js
- front-end/src/home/PostDetail.css
- front-end/src/home/PostDetail.js
created post detail page. Can be viewed via "/detail"
> User story/120/task/63/postdetail

- front-end/src/App.js
- front-end/src/auxiliary/Browse.css
- front-end/src/auxiliary/Browse.js
- front-end/src/auxiliary/NameTag.css
- front-end/src/auxiliary/PostContent.js
- front-end/src/home/Edit.css
- front-end/src/home/Edit.js
- front-end/src/home/Home.js
- front-end/src/me/Browse_History.css
- front-end/src/me/Browse_History.js
- front-end/src/me/Friend_Suggestion.css
- front-end/src/me/Friend_Suggestion.js
- front-end/src/me/Me.js
- update: minor css change
- Task #55: implemented post edit page: user story #45
- Task #98: implemented browse history page: user story #28
- Task #61: implemented friend suggestion page: user story #26
> User story/26 28 45/task/55 61 98/browse history friend suggestion post edit 2

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/auxiliary/Commented.js
- front-end/src/community/Commented_List.js
- front-end/src/community/Community.css
- front-end/src/me/Me.css
- front-end/src/me/Me.js
> User story/125 127/task/124/build me page

- front-end/src/App.js
- front-end/src/me/Me.css
- front-end/src/me/Me.js
- front-end/src/me/MyProfile.css
- front-end/src/me/MyProfile.js
* build main content and css of my profile page
> User story/126/task/64/build profile me page

- front-end/src/me/MyProfile.js
* add post content to my profile page
> User story/126/task/64/build friend profile page

- front-end/src/App.js
- front-end/src/auxiliary/PostContent.js
- front-end/src/home/Edit.js
- front-end/src/me/FriendProfile.js
- front-end/src/me/MyProfile.js
* Fix:link `edie_new_post` in `my_profile` page #64
* Fix:delete `create_post` button in `friend_profile` page #64
* Fix:link `back` and `send` button to previous page in `edit_new_post` page #55
* Fix:link post in `PostContent` component to `detailpost` page #78
> User story/126/task/64/build profile me page2

- front-end/src/auxiliary/NavBar/MainNav.css
- front-end/src/auxiliary/PostContent.css
- front-end/src/auxiliary/PostContent.js
- front-end/src/auxiliary/ToComment.css
- front-end/src/auxiliary/ToComment.js
* update css of comment, like and repost of `PostContent` component
* fix links in `PostContent` component
* update css of `ToComment.css` 
* add current time when the comment sent in `ToComment.js` and `ToComment.css`
> Spike/146/fix css of post content and add comment record and date.

- front-end/src/App.js
- front-end/src/auxiliary/NavBar/HomeNav.css
- front-end/src/auxiliary/NavBar/HomeNav.js
- front-end/src/auxiliary/NavBar/MainNav.css
- front-end/src/auxiliary/PostContent.css
- front-end/src/auxiliary/ToRepost.css
- front-end/src/auxiliary/ToRepost.js
- front-end/src/home/Edit.css
- front-end/src/home/Edit.js
- front-end/src/home/Repost.css
- front-end/src/home/Repost.js
- Added 'filter' and 'new post' buttons to home nav
- Implemented repost page according to user story #45
- minor changes
> User story/45/task/55/repost page

- front-end/src/App.js
- front-end/src/auxiliary/Browse.js
- front-end/src/auxiliary/NameTag.js
- front-end/src/auxiliary/NavBar/HomeNav.css
- front-end/src/auxiliary/NavBar/HomeNav.js
- front-end/src/auxiliary/ToRepost.js
- front-end/src/community/Mentions.css
- front-end/src/community/Mentions.js
- front-end/src/community/Mentions_List.css
- front-end/src/community/Mentions_List.js
- front-end/src/home/Edit.css
- front-end/src/home/Edit.js
- front-end/src/home/Repost.css
- front-end/src/home/Repost.js
- front-end/src/me/Browse_History.css
- front-end/src/me/Browse_History.js
- front-end/src/me/Friend_Suggestion.js
- front-end/src/me/Liked.css
- front-end/src/me/Liked.js
- front-end/src/me/Liked_List.css
- front-end/src/me/Liked_List.js
- implemented liked & mentioned history page
- linked profile images in 'browse history' and 'friend suggestions' to friend profile page
- fixed some errors
- css modifications
> User story/27 104/task/71 96/liked mentioned etc

- back-end/package-lock.json
- back-end/package.json
install packages for back-end development(axios,body-parser,chai,dotenv,mocha,morgan,multer,ngrok,postman,pug) #160
> Add: install packages for back-end development #160

- back-end/app.js
- front-end/package.json
- front-end/src/community/Commented_List.js
- front-end/src/home/RecentlyVisited.js
- front-end/src/home/Recommended.js
- front-end/src/home/WhatsNew.js
change port of react to 4000. #160
change to axios('http://localhost:3000/')
> change port of react to 4000. #160

- front-end/package.json
reclaimed proxy to jason package
> Add: package add proxy

- front-end/src/me/Me.css
- front-end/src/me/Me.js
click a connected button, it will change to connect.
click a connect button, it will change to connected.
> Update: connect-connected feature added in Me page

- back-end/app.js
- front-end/src/me/My_Comment_History_List.js
add `my_comment_history` router in `app.js` in backend  #165
modify axios in `My_Comment_History` in frontend to send request to `my_comment_history` router of backend.
> Update: build my comment history backend and modify frontend corresponding code

- back-end/app.js
- front-end/src/community/Chat.js
- front-end/src/community/Community.js
- front-end/src/home/WhatsNew.js
-Community page gets data from backend
-chat page press submit save new messages to data --> push to backend
-commented out data passing in What's new page for direct visit
> User story/46/task/171

- back-end/app.js
- front-end/src/auxiliary/Browse.js
- front-end/src/home/PostDetail.js
- front-end/src/me/Browse_History.js
-Send post data with view time to backend when user click post detail
-Get browse data from backend on browse history list(fake data for now)
> User story/27/task/181

- back-end/app.js
- front-end/src/auxiliary/NavBar/HomeNav.js
- front-end/src/home/WhatsNew.js
to see posts only from social media selected in the filter#254
> Update: homa page/home nav filter

- back-end/app.js
- back-end/db.js
- back-end/loginAuth/passPortConfig.js
- back-end/loginAuth/user.js
- front-end/src/auxiliary/Loginform.js
- front-end/src/auxiliary/Signupform.js
When user register from sign up page, the server would connect to mongodb and write a new user entry to user database. If a user is successfully created, he/she would be redirected to the main page. 
Since we are using user name as unique id, if there is a duplicated name, registration would not be successful. 
Samething with login: we check if password matches with username/ username exists in db; if success, user would be redirected to main page
> User story/53/task/288

- back-end/app.js
- back-end/postData/post.js
- back-end/userInfo/userInfo.js
- front-end/src/auxiliary/Signupform.js
- front-end/src/home/PostDetail.js
-changed userinfo schema
-create userinfo when registered
-update browsed postid when user click post detail (hard coded id for now)
> User story/120/task/311

- back-end/app.js
- back-end/db.js
- back-end/userInfo/userInfo.js
1.userInfo Schema update. 
2.update initial userInfo data when a new user registers. 
3.update get_me api in back-end to retrieve user_info from database and send to front-end
> User-story/127/324/Me-page-database

- back-end/app.js
- back-end/userInfo/userInfo.js
- front-end/src/me/MyProfile.js
implemented edit post database. (only post to O-Zone now)
implemented my profile database. (show all the O-Zone post user posted on their profile page)
> User story/45/task/293/edit post database

- back-end/app.js
- back-end/package.json
- front-end/src/auxiliary/NameTag.css
- front-end/src/auxiliary/NameTag.js
- front-end/src/me/Friend_Suggestion.js
In the `/friend_suggestion` page, if the user click `follow button` to follow a new friend or `unfollow button` to unfollow an old friend, database is updated. 
search friend bar is disabled now, which will be implemented later.
> User story/26/task/310/friend suggestion database

- back-end/app.js
- front-end/src/me/FriendProfile.js
friend_profile database finished. Now click the user photo of the user which you have followed in the`/friend_suggestion` page will go to your friend profile page. 
Note: the users in home page is not valid as they are not registered in our db. Click their user photo in home page will cause error.
> User story/127/task/300/friend profile database

- back-end/app.js
- back-end/package.json
- front-end/src/auxiliary/PostContent.js
- front-end/src/home/Edit.js
- front-end/src/me/Background_picture.js
- front-end/src/me/MyProfile.js
background_picture database finished.
> User story/342/task/296/comment in post database

- back-end/app.js
- front-end/src/home/RecentlyVisited.js
- front-end/src/home/Recommended.js
- front-end/src/home/WhatsNew.js
- Implemented database for what's new and recommended pages
- minor fix
> User story/26 50/task/308 309/recommend and whatsnew db

- back-end/app.js
- back-end/userInfo/userInfo.js
- front-end/src/auxiliary/Commented.js
- front-end/src/auxiliary/PostContent.js
- front-end/src/auxiliary/ToComment.js
- front-end/src/me/My_Comment_History.js
my comment history finished. #291 
commented history database finished. #297 
comment in post content database finished. #296
comment in post detail will be implemented later
> User story/342/task/296/comment database

- back-end/app.js
- back-end/package.json
- front-end/src/auxiliary/PostContent.js
- front-end/src/auxiliary/ToRepost.js
- front-end/src/community/Mentions.js
- front-end/src/home/Repost.js
1. fast repost database finished. Users can click fast repost. Then the post is directly added to the user's o-zone post_data and shown on the profile page.
2. repost database finished. Users can add a message to other user's posts. and then repost the post with a message. 
3.  retrieve friend and linked_platform from database to be shown in repost component.
> User story/371/task/312/repost database

- back-end/app.js
- front-end/src/search/SearchBar.js
- front-end/src/search/SearchRecommended.js
- front-end/src/search/SearchResult.js
- front-end/src/search/Trending.js
- Implemented databases for trending and search functions
- What's New now includes posts from user him/herself
- Other minor changes
> Task/302 303/trending and search result database

- back-end/app.js
- front-end/src/auxiliary/ToRepost.js
refresh page after fast repost.
fix a minor error.
> Fix: refresh page after fast repost. #312

- back-end/app.js
- front-end/src/auxiliary/Browse.js
- front-end/src/auxiliary/PostContent_noAction.css
- front-end/src/community/Community.css
- front-end/src/community/NewChat.js
- front-end/src/home/Repost.css
- front-end/src/home/Repost.js
- front-end/src/me/Browse_History.css
- front-end/src/me/Browse_History.js
- front-end/src/me/Followers.css
- front-end/src/me/Followers.js
- front-end/src/me/Followings.css
- front-end/src/me/Followings.js
- front-end/src/me/Friend_Suggestion.css
- front-end/src/me/Friend_Suggestion.js
- front-end/src/me/MyProfile.css
- front-end/src/me/My_Comment_History_List.css
- front-end/src/search/SearchBar.css
- front-end/src/search/SearchBar.js
- front-end/src/search/SearchRecommended.css
- front-end/src/search/Trending.css
> Update: update css

- back-end/app.js
- front-end/src/home/WhatsNew.js
if the user is not login, redirect to prelogin page.
> login check

- .travis.yml
- README.md
- back-end/README.md
> Add: travis setup #392

- back-end/router/home/edit.js
- back-end/router/me/facebook.js
- back-end/router/me/instagram.js
- front-end/src/home/Edit.js
- front-end/src/home/Repost.js
- front-end/src/me/InstagramAuth.js
- front-end/src/me/TwitterAuth.js
Reverts agile-dev-assignments/project-setup-team-ikedacho-visionary#467
> Revert "Spike/414/instagram"
